// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Protocol.proto</summary>
  public static partial class ProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for Protocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Qcm90b2NvbC5wcm90bxIIUHJvdG9jb2wiIwoTV2ViU29ja2V0UGFja2V0",
            "VGVzdBIMCgRUeXBlGAEgASgNImYKIldlYlNvY2tldFNlcnZlclJlc3BvbnNl",
            "QWZ0ZXJPbk9wZW4SDAoEVHlwZRgBIAEoDRIcChRDbGllbnRDb25uZWN0aW9u",
            "R3VpZBgCIAEoCRIUCgxIZWxsb01lc3NhZ2UYAyABKAkiagooV2ViU29ja2V0",
            "Q2xpZW50UmVxdWVzdFZhbGlkYXRlQ29udHJvbEtleRIMCgRUeXBlGAEgASgN",
            "EhwKFENsaWVudENvbm5lY3Rpb25HdWlkGAIgASgJEhIKCkNvbnRyb2xLZXkY",
            "AyABKAkihgEKKVdlYlNvY2tldFNlcnZlclJlc3BvbnNlVmFsaWRhdGVDb250",
            "cm9sS2V5EgwKBFR5cGUYASABKA0SHAoUQ2xpZW50Q29ubmVjdGlvbkd1aWQY",
            "AiABKAkSEgoKVmFsaWRhdGlvbhgDIAEoCBIZChFWYWxpZGF0aW9uTWVzc2Fn",
            "ZRgEIAEoCUICSAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.WebSocketPacketTest), global::Protocol.WebSocketPacketTest.Parser, new[]{ "Type" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.WebSocketServerResponseAfterOnOpen), global::Protocol.WebSocketServerResponseAfterOnOpen.Parser, new[]{ "Type", "ClientConnectionGuid", "HelloMessage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.WebSocketClientRequestValidateControlKey), global::Protocol.WebSocketClientRequestValidateControlKey.Parser, new[]{ "Type", "ClientConnectionGuid", "ControlKey" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.WebSocketServerResponseValidateControlKey), global::Protocol.WebSocketServerResponseValidateControlKey.Parser, new[]{ "Type", "ClientConnectionGuid", "Validation", "ValidationMessage" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 1xxx 代表客户端=>服务端
  /// 2xxx 代表服务端=>客户端
  /// </summary>
  public sealed partial class WebSocketPacketTest : pb::IMessage<WebSocketPacketTest> {
    private static readonly pb::MessageParser<WebSocketPacketTest> _parser = new pb::MessageParser<WebSocketPacketTest>(() => new WebSocketPacketTest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WebSocketPacketTest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketPacketTest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketPacketTest(WebSocketPacketTest other) : this() {
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketPacketTest Clone() {
      return new WebSocketPacketTest(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private uint type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WebSocketPacketTest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WebSocketPacketTest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WebSocketPacketTest other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Type 2001
  /// 服务端响应客户端链接事件,并回复给客户端
  /// </summary>
  public sealed partial class WebSocketServerResponseAfterOnOpen : pb::IMessage<WebSocketServerResponseAfterOnOpen> {
    private static readonly pb::MessageParser<WebSocketServerResponseAfterOnOpen> _parser = new pb::MessageParser<WebSocketServerResponseAfterOnOpen>(() => new WebSocketServerResponseAfterOnOpen());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WebSocketServerResponseAfterOnOpen> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketServerResponseAfterOnOpen() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketServerResponseAfterOnOpen(WebSocketServerResponseAfterOnOpen other) : this() {
      type_ = other.type_;
      clientConnectionGuid_ = other.clientConnectionGuid_;
      helloMessage_ = other.helloMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketServerResponseAfterOnOpen Clone() {
      return new WebSocketServerResponseAfterOnOpen(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private uint type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "ClientConnectionGuid" field.</summary>
    public const int ClientConnectionGuidFieldNumber = 2;
    private string clientConnectionGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientConnectionGuid {
      get { return clientConnectionGuid_; }
      set {
        clientConnectionGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HelloMessage" field.</summary>
    public const int HelloMessageFieldNumber = 3;
    private string helloMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HelloMessage {
      get { return helloMessage_; }
      set {
        helloMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WebSocketServerResponseAfterOnOpen);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WebSocketServerResponseAfterOnOpen other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (ClientConnectionGuid != other.ClientConnectionGuid) return false;
      if (HelloMessage != other.HelloMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (ClientConnectionGuid.Length != 0) hash ^= ClientConnectionGuid.GetHashCode();
      if (HelloMessage.Length != 0) hash ^= HelloMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Type);
      }
      if (ClientConnectionGuid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ClientConnectionGuid);
      }
      if (HelloMessage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(HelloMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
      }
      if (ClientConnectionGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientConnectionGuid);
      }
      if (HelloMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HelloMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WebSocketServerResponseAfterOnOpen other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.ClientConnectionGuid.Length != 0) {
        ClientConnectionGuid = other.ClientConnectionGuid;
      }
      if (other.HelloMessage.Length != 0) {
        HelloMessage = other.HelloMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = input.ReadUInt32();
            break;
          }
          case 18: {
            ClientConnectionGuid = input.ReadString();
            break;
          }
          case 26: {
            HelloMessage = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Type 1002
  /// 客户端向服务端请求验证ControlKey
  /// </summary>
  public sealed partial class WebSocketClientRequestValidateControlKey : pb::IMessage<WebSocketClientRequestValidateControlKey> {
    private static readonly pb::MessageParser<WebSocketClientRequestValidateControlKey> _parser = new pb::MessageParser<WebSocketClientRequestValidateControlKey>(() => new WebSocketClientRequestValidateControlKey());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WebSocketClientRequestValidateControlKey> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketClientRequestValidateControlKey() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketClientRequestValidateControlKey(WebSocketClientRequestValidateControlKey other) : this() {
      type_ = other.type_;
      clientConnectionGuid_ = other.clientConnectionGuid_;
      controlKey_ = other.controlKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketClientRequestValidateControlKey Clone() {
      return new WebSocketClientRequestValidateControlKey(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private uint type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "ClientConnectionGuid" field.</summary>
    public const int ClientConnectionGuidFieldNumber = 2;
    private string clientConnectionGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientConnectionGuid {
      get { return clientConnectionGuid_; }
      set {
        clientConnectionGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ControlKey" field.</summary>
    public const int ControlKeyFieldNumber = 3;
    private string controlKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ControlKey {
      get { return controlKey_; }
      set {
        controlKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WebSocketClientRequestValidateControlKey);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WebSocketClientRequestValidateControlKey other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (ClientConnectionGuid != other.ClientConnectionGuid) return false;
      if (ControlKey != other.ControlKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (ClientConnectionGuid.Length != 0) hash ^= ClientConnectionGuid.GetHashCode();
      if (ControlKey.Length != 0) hash ^= ControlKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Type);
      }
      if (ClientConnectionGuid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ClientConnectionGuid);
      }
      if (ControlKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ControlKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
      }
      if (ClientConnectionGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientConnectionGuid);
      }
      if (ControlKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ControlKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WebSocketClientRequestValidateControlKey other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.ClientConnectionGuid.Length != 0) {
        ClientConnectionGuid = other.ClientConnectionGuid;
      }
      if (other.ControlKey.Length != 0) {
        ControlKey = other.ControlKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = input.ReadUInt32();
            break;
          }
          case 18: {
            ClientConnectionGuid = input.ReadString();
            break;
          }
          case 26: {
            ControlKey = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Type 2002
  /// 服务端回复客户端ControlKey验证结果
  /// </summary>
  public sealed partial class WebSocketServerResponseValidateControlKey : pb::IMessage<WebSocketServerResponseValidateControlKey> {
    private static readonly pb::MessageParser<WebSocketServerResponseValidateControlKey> _parser = new pb::MessageParser<WebSocketServerResponseValidateControlKey>(() => new WebSocketServerResponseValidateControlKey());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WebSocketServerResponseValidateControlKey> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketServerResponseValidateControlKey() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketServerResponseValidateControlKey(WebSocketServerResponseValidateControlKey other) : this() {
      type_ = other.type_;
      clientConnectionGuid_ = other.clientConnectionGuid_;
      validation_ = other.validation_;
      validationMessage_ = other.validationMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WebSocketServerResponseValidateControlKey Clone() {
      return new WebSocketServerResponseValidateControlKey(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private uint type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "ClientConnectionGuid" field.</summary>
    public const int ClientConnectionGuidFieldNumber = 2;
    private string clientConnectionGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientConnectionGuid {
      get { return clientConnectionGuid_; }
      set {
        clientConnectionGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Validation" field.</summary>
    public const int ValidationFieldNumber = 3;
    private bool validation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Validation {
      get { return validation_; }
      set {
        validation_ = value;
      }
    }

    /// <summary>Field number for the "ValidationMessage" field.</summary>
    public const int ValidationMessageFieldNumber = 4;
    private string validationMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ValidationMessage {
      get { return validationMessage_; }
      set {
        validationMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WebSocketServerResponseValidateControlKey);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WebSocketServerResponseValidateControlKey other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (ClientConnectionGuid != other.ClientConnectionGuid) return false;
      if (Validation != other.Validation) return false;
      if (ValidationMessage != other.ValidationMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (ClientConnectionGuid.Length != 0) hash ^= ClientConnectionGuid.GetHashCode();
      if (Validation != false) hash ^= Validation.GetHashCode();
      if (ValidationMessage.Length != 0) hash ^= ValidationMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Type);
      }
      if (ClientConnectionGuid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ClientConnectionGuid);
      }
      if (Validation != false) {
        output.WriteRawTag(24);
        output.WriteBool(Validation);
      }
      if (ValidationMessage.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ValidationMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
      }
      if (ClientConnectionGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientConnectionGuid);
      }
      if (Validation != false) {
        size += 1 + 1;
      }
      if (ValidationMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ValidationMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WebSocketServerResponseValidateControlKey other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.ClientConnectionGuid.Length != 0) {
        ClientConnectionGuid = other.ClientConnectionGuid;
      }
      if (other.Validation != false) {
        Validation = other.Validation;
      }
      if (other.ValidationMessage.Length != 0) {
        ValidationMessage = other.ValidationMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = input.ReadUInt32();
            break;
          }
          case 18: {
            ClientConnectionGuid = input.ReadString();
            break;
          }
          case 24: {
            Validation = input.ReadBool();
            break;
          }
          case 34: {
            ValidationMessage = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
